apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: metadata.integration
      http:
        paths:
          - backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  number: 80
            path: /
            pathType: Prefix
