openapi: 3.1.0
info:
  title: GLACIATION Metadata Service
  description: The service exposes API to work with Distributed Knowledge Graph
  license:
    name: MIT License
    url: https://github.com/glaciation-heu/glaciaition-metadata-service/blob/main/LICENSE
  version: 0.1.0
paths:
  /api/v0/graph:
    patch:
      tags:
      - Graph
      summary: Update Graph
      description: Update Distributed Knowledge Graph
      operationId: update_graph_api_v0_graph_patch
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Update Graph Api V0 Graph Patch
  /metrics:
    get:
      tags:
      - Monitoring
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
